/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 21-Dec-2021 2:45:59 PM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */
USE master
CREATE DATABASE QLGH
GO

USE QLGH
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_ChiNhanh_DoiTac]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [ChiNhanh] DROP CONSTRAINT [FK_ChiNhanh_DoiTac]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_CT_DonHang_DonHang]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [CT_DonHang] DROP CONSTRAINT [FK_CT_DonHang_DonHang]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_CT_DonHang_SanPham]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [CT_DonHang] DROP CONSTRAINT [FK_CT_DonHang_SanPham]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_CT_HopDong_ChiNhanh]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [CT_HopDong] DROP CONSTRAINT [FK_CT_HopDong_ChiNhanh]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_CT_HopDong_HopDong]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [CT_HopDong] DROP CONSTRAINT [FK_CT_HopDong_HopDong]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_DoiTac_TaiKhoan]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [DoiTac] DROP CONSTRAINT [FK_DoiTac_TaiKhoan]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_DonHang_DoiTac]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [DonHang] DROP CONSTRAINT [FK_DonHang_DoiTac]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_DonHang_KhachHang]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [DonHang] DROP CONSTRAINT [FK_DonHang_KhachHang]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_DonHang_TaiXe]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [DonHang] DROP CONSTRAINT [FK_DonHang_TaiXe]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_HopDong_DoiTac]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [HopDong] DROP CONSTRAINT [FK_HopDong_DoiTac]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_HopDong_NhanVien]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [HopDong] DROP CONSTRAINT [FK_HopDong_NhanVien]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_KhachHang_TaiKhoan]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [KhachHang] DROP CONSTRAINT [FK_KhachHang_TaiKhoan]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_NhanVien_TaiKhoan]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [NhanVien] DROP CONSTRAINT [FK_NhanVien_TaiKhoan]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_SanPhamChiNhanh_ChiNhanh]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [SanPhamChiNhanh] DROP CONSTRAINT [FK_SanPhamChiNhanh_ChiNhanh]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_SanPhamChiNhanh_SanPham]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [SanPhamChiNhanh] DROP CONSTRAINT [FK_SanPhamChiNhanh_SanPham]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_TaiXe_TaiKhoan]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [TaiXe] DROP CONSTRAINT [FK_TaiXe_TaiKhoan]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[ChiNhanh]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [ChiNhanh]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CT_DonHang]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [CT_DonHang]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CT_HopDong]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [CT_HopDong]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[DoiTac]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [DoiTac]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[DonHang]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [DonHang]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[HopDong]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [HopDong]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[KhachHang]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [KhachHang]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[NhanVien]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [NhanVien]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[SanPham]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [SanPham]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[SanPhamChiNhanh]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [SanPhamChiNhanh]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TaiKhoan]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TaiKhoan]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TaiXe]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TaiXe]
GO

/* Create Tables */

CREATE TABLE [ChiNhanh]
(
	[MaDT] char(10) NOT NULL,
	[MaCN] char(10) NOT NULL,
	[TenCN] nvarchar(50) NULL,
	[DiaChi] nvarchar(50) NULL
)
GO

CREATE TABLE [CT_DonHang]
(
	[MaDH] char(10) NOT NULL,
	[MaSP] char(10) NOT NULL,
	[SoLuong] int NULL,
	[GiaBan] int NULL,
	[ThanhTien] int NULL
)
GO

CREATE TABLE [CT_HopDong]
(
	[MaHD] char(10) NOT NULL,
	[MaDT] char(10) NOT NULL,
	[MaCN] char(10) NOT NULL,
	[DiaChi] nvarchar(100) NULL
)
GO

CREATE TABLE [DoiTac]
(
	[MaDT] char(10) NOT NULL,
	[TenDT] nvarchar(50) NULL,
	[NguoiDaiDien] nvarchar(50) NULL,
	[ThanhPho] nvarchar(50) NULL,
	[Quan] nvarchar(50) NULL,
	[SoChiNhanh] int NULL,
	[SoLuongDonMoiNgay] int NULL,
	[LoaiHangVanChuyen] nvarchar(50) NULL,
	[DiaChiKinhDoanh] nvarchar(100) NULL,
	[SoDienThoai] varchar(12) NULL,
	[Email] varchar(50) NULL,
	[TaiKhoan] varchar(50) NULL
)
GO

CREATE TABLE [DonHang]
(
	[MaDH] char(10) NOT NULL,
	[HTThanhToan] nvarchar(50) NULL,
	[DiaChiGiaoHang] nvarchar(100) NULL,
	[MaKH] char(10) NULL,
	[TinhTrang] nvarchar(50) NULL,
	[MaTX] char(10) NULL,
	[MaDT] char(10) NULL,
	[TongTien] int NULL,
	[NgayLap] date NOT NULL
)
GO

CREATE TABLE [HopDong]
(
	[MaHD] char(10) NOT NULL,
	[MaSoThueDT] varchar(13) NULL,
	[NguoiDaiDien] nvarchar(50) NULL,
	[SoChiNhanhDK] int NULL,
	[MaDT] char(10) NULL,
	[ThoiHan] date NULL,
	[MaNV] char(10) NULL
)
GO

CREATE TABLE [KhachHang]
(
	[MaKH] char(10) NOT NULL,
	[HoTen] nvarchar(50) NULL,
	[SDT] varchar(12) NULL,
	[DiaChi] nvarchar(100) NULL,
	[Email] varchar(50) NULL,
	[TaiKhoan] varchar(50) NULL
)
GO

CREATE TABLE [NhanVien]
(
	[MaNV] char(10) NOT NULL,
	[TenNV] nvarchar(50) NULL,
	[TaiKhoan] varchar(50) NULL
)
GO

CREATE TABLE [SanPham]
(
	[MaSP] char(10) NOT NULL,
	[TenSP] nvarchar(50) NULL,
	[GiaBan] int NULL
)
GO

CREATE TABLE [SanPhamChiNhanh]
(
	[MaDT] char(10) NOT NULL,
	[MaCN] char(10) NOT NULL,
	[MaSP] char(10) NOT NULL,
	[SLTon] int NULL
)
GO

CREATE TABLE [TaiKhoan]
(
	[TaiKhoan] varchar(50) NOT NULL,
	[MatKhau] varchar(20) NOT NULL,
	[NguoiDung] nvarchar(50) NOT NULL,
	[VaiTro] nvarchar(20) NOT NULL,
	[TrangThai] varchar(10) NOT NULL
)
GO

CREATE TABLE [TaiXe]
(
	[MaTX] char(10) NOT NULL,
	[HoTen] nvarchar(50) NULL,
	[CMND] varchar(12) NULL,
	[SDT] varchar(12) NULL,
	[DiaChi] nvarchar(100) NULL,
	[BienSoXe] varchar(15) NULL,
	[KhuVucHoatDong] nvarchar(50) NULL,
	[Email] varchar(50) NULL,
	[TTNganHang] varchar(15) NULL,
	[TaiKhoan] varchar(50) NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [ChiNhanh] 
 ADD CONSTRAINT [PK_ChiNhanh]
	PRIMARY KEY CLUSTERED ([MaCN] ASC,[MaDT] ASC)
GO

ALTER TABLE [CT_DonHang] 
 ADD CONSTRAINT [PK_CT_DonHang]
	PRIMARY KEY CLUSTERED ([MaDH] ASC,[MaSP] ASC)
GO

ALTER TABLE [CT_HopDong] 
 ADD CONSTRAINT [PK_CT_HopDong]
	PRIMARY KEY CLUSTERED ([MaCN] ASC,[MaHD] ASC,[MaDT] ASC)
GO

ALTER TABLE [DoiTac] 
 ADD CONSTRAINT [PK_DoiTac]
	PRIMARY KEY CLUSTERED ([MaDT] ASC)
GO

ALTER TABLE [DonHang] 
 ADD CONSTRAINT [PK_DonHang]
	PRIMARY KEY CLUSTERED ([MaDH] ASC)
GO

ALTER TABLE [HopDong] 
 ADD CONSTRAINT [PK_HopDong]
	PRIMARY KEY CLUSTERED ([MaHD] ASC)
GO

ALTER TABLE [KhachHang] 
 ADD CONSTRAINT [PK_KhachHang]
	PRIMARY KEY CLUSTERED ([MaKH] ASC)
GO

ALTER TABLE [NhanVien] 
 ADD CONSTRAINT [PK_NhanVien]
	PRIMARY KEY CLUSTERED ([MaNV] ASC)
GO

ALTER TABLE [SanPham] 
 ADD CONSTRAINT [PK_SanPham]
	PRIMARY KEY CLUSTERED ([MaSP] ASC)
GO

ALTER TABLE [SanPhamChiNhanh] 
 ADD CONSTRAINT [PK_SanPhamChiNhanh]
	PRIMARY KEY CLUSTERED ([MaDT] ASC,[MaCN] ASC,[MaSP] ASC)
GO

ALTER TABLE [TaiKhoan] 
 ADD CONSTRAINT [PK_TaiKhoan]
	PRIMARY KEY CLUSTERED ([TaiKhoan] ASC)
GO

ALTER TABLE [TaiXe] 
 ADD CONSTRAINT [PK_TaiXe]
	PRIMARY KEY CLUSTERED ([MaTX] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [ChiNhanh] ADD CONSTRAINT [FK_ChiNhanh_DoiTac]
	FOREIGN KEY ([MaDT]) REFERENCES [DoiTac] ([MaDT]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [CT_DonHang] ADD CONSTRAINT [FK_CT_DonHang_DonHang]
	FOREIGN KEY ([MaDH]) REFERENCES [DonHang] ([MaDH]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [CT_DonHang] ADD CONSTRAINT [FK_CT_DonHang_SanPham]
	FOREIGN KEY ([MaSP]) REFERENCES [SanPham] ([MaSP]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [CT_HopDong] ADD CONSTRAINT [FK_CT_HopDong_ChiNhanh]
	FOREIGN KEY ([MaCN],[MaDT]) REFERENCES [ChiNhanh] ([MaCN],[MaDT]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [CT_HopDong] ADD CONSTRAINT [FK_CT_HopDong_HopDong]
	FOREIGN KEY ([MaHD]) REFERENCES [HopDong] ([MaHD]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [DoiTac] ADD CONSTRAINT [FK_DoiTac_TaiKhoan]
	FOREIGN KEY ([TaiKhoan]) REFERENCES [TaiKhoan] ([TaiKhoan]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [DonHang] ADD CONSTRAINT [FK_DonHang_DoiTac]
	FOREIGN KEY ([MaDT]) REFERENCES [DoiTac] ([MaDT]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [DonHang] ADD CONSTRAINT [FK_DonHang_KhachHang]
	FOREIGN KEY ([MaKH]) REFERENCES [KhachHang] ([MaKH]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [DonHang] ADD CONSTRAINT [FK_DonHang_TaiXe]
	FOREIGN KEY ([MaTX]) REFERENCES [TaiXe] ([MaTX]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [HopDong] ADD CONSTRAINT [FK_HopDong_DoiTac]
	FOREIGN KEY ([MaDT]) REFERENCES [DoiTac] ([MaDT]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [HopDong] ADD CONSTRAINT [FK_HopDong_NhanVien]
	FOREIGN KEY ([MaNV]) REFERENCES [NhanVien] ([MaNV]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [KhachHang] ADD CONSTRAINT [FK_KhachHang_TaiKhoan]
	FOREIGN KEY ([TaiKhoan]) REFERENCES [TaiKhoan] ([TaiKhoan]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [NhanVien] ADD CONSTRAINT [FK_NhanVien_TaiKhoan]
	FOREIGN KEY ([TaiKhoan]) REFERENCES [TaiKhoan] ([TaiKhoan]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [SanPhamChiNhanh] ADD CONSTRAINT [FK_SanPhamChiNhanh_ChiNhanh]
	FOREIGN KEY ([MaCN],[MaDT]) REFERENCES [ChiNhanh] ([MaCN],[MaDT]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [SanPhamChiNhanh] ADD CONSTRAINT [FK_SanPhamChiNhanh_SanPham]
	FOREIGN KEY ([MaSP]) REFERENCES [SanPham] ([MaSP]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [TaiXe] ADD CONSTRAINT [FK_TaiXe_TaiKhoan]
	FOREIGN KEY ([TaiKhoan]) REFERENCES [TaiKhoan] ([TaiKhoan]) ON DELETE No Action ON UPDATE No Action
GO
